name: Post announcement discussions to Google Chat
on:
  discussion:
    types: [created]
jobs:
  notify:
    runs-on: ubuntu-latest
    if: ${{ github.event.discussion.category.name == 'Announcements' || github.event.discussion.category.slug == 'announcements' }}
    steps:
      - name: Post to Google Chat
        env:
          WEBHOOK: https://chat.googleapis.com/v1/spaces/AAQAYB1iDxg/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=M_ei1YkjB37rQL4wBvVRpFj4KKrbBHp0ISm1QITBokk
          REPO: ${{ github.repository }}
          TITLE: ${{ github.event.discussion.title }}
          URL: ${{ github.event.discussion.html_url }}
        run: |
          payload=$(jq -n --arg repo "$REPO" --arg title "$TITLE" --arg url "$URL" \
            '{text: ($repo + ": New announcement — " + $title + " — " + $url)}')
          curl -X POST -H "Content-Type: application/json" -d "$payload" "$WEBHOOK"
